# Generated by Django 4.1 on 2023-01-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='23-01-03', max_length=20, verbose_name='出库日期')),
                ('flange_specifications', models.TextField(verbose_name='品名')),
                ('flange_varieties', models.TextField(verbose_name='规格')),
                ('flange_single_price', models.FloatField(verbose_name='单价')),
                ('order_nums', models.IntegerField(verbose_name='数量')),
                ('order_sum', models.FloatField(verbose_name='订单总价')),
                ('customer', models.TextField(verbose_name='提货单位')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('flange_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='23-01-03', max_length=20, verbose_name='更新日期')),
                ('flange_specifications', models.TextField(verbose_name='品名')),
                ('flange_varieties', models.TextField(verbose_name='规格')),
                ('flange_single_price', models.FloatField(verbose_name='单价')),
                ('stocks_nums', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '价目表',
                'verbose_name_plural': '价目表',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flange_specifications', models.TextField(verbose_name='品名')),
            ],
            options={
                'verbose_name': '型号',
                'verbose_name_plural': '型号',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flange_specifications', models.TextField(verbose_name='品名')),
                ('flange_varieties', models.TextField(verbose_name='规格')),
                ('order_nums', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='23-01-03', max_length=20, verbose_name='更新日期')),
                ('flange_specifications', models.TextField(verbose_name='品名')),
                ('flange_varieties', models.TextField(verbose_name='规格')),
                ('flange_single_price', models.FloatField(verbose_name='单价')),
                ('order_nums', models.IntegerField(verbose_name='数量')),
                ('order_sum', models.FloatField(verbose_name='订单总价')),
                ('provider', models.TextField(verbose_name='供货商')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
            },
        ),
    ]
